replicaCount: 2
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - apps2.react.pronchev.com
  tls:
    - secretName: apps-ingress-tls
      hosts:
        - apps2.react.pronchev.com
