git-repo:
  name: vpronchev/React
  access-token: 
  uri: git@github.com:vpronchev/React.git
  private-key: |
    -----BEGIN RSA PRIVATE KEY-----
    -----END RSA PRIVATE KEY-----
docker-registry:
  uri: vpronchev.com/demo-app-2983e16/React
  username: _json_key
  password: |
    {
    "type": "service_account",
    "project_id": "XXX",
    "private_key_id": "XXX",
    "private_key": "XXX",
    "client_email": "XXX",
    "client_id": "XXX",
    "auth_uri": "XXX",
    "token_uri": "XXX",
    "auth_provider_x509_cert_url": "XXX",
    "client_x509_cert_url": "XXX"
    }
  cache: "false"
  cache-tag: latest

chart-repo:
  uri: vpronchev.github.com/helmcharts
  name: React
  chart: React

master-release:
  name: ci/helm-release/master-release.txt
  values: ci/helm-release/master-values.yaml

production-release:
  name: ci/helm-release/production-release.txt
  values: ci/helm-release/production-values.yaml

gcloud-master:
  project: React
  zone: europe-west1-d
  cluster: k8s-cluster
  auth: |
    {
    "type": "service_account",
    "project_id": "XXX",
    "private_key_id": "XXX",
    "private_key": "XXX",
    "client_email": "XXX",
    "client_id": "XXX",
    "auth_uri": "XXX",
    "token_uri": "XXX",
    "auth_provider_x509_cert_url": "XXX",
    "client_x509_cert_url": "XXX"
    }
gcloud-production:
  project: React
  zone: europe-west1-d
  cluster: k8s-cluster
  auth: |
    {
    "type": "service_account",
    "project_id": "XXX",
    "private_key_id": "XXX",
    "private_key": "XXX",
    "client_email": "XXX",
    "client_id": "XXX",
    "auth_uri": "XXX",
    "token_uri": "XXX",
    "auth_provider_x509_cert_url": "XXX",
    "client_x509_cert_url": "XXX"
    }
helm-master:
  ca: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  cert: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  key: |
    -----BEGIN EC PRIVATE KEY-----
    -----END EC PRIVATE KEY-----
helm-production:
  ca: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  cert: |
    -----BEGIN CERTIFICATE-----
    
    -----END CERTIFICATE-----
  key: |
    -----BEGIN EC PRIVATE KEY-----
    -----END EC PRIVATE KEY-----
